-- MySQL Script generated by MySQL Workbench 1
-- Wed Feb 17 20:55:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reegalo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reegalo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reegalo` DEFAULT CHARACTER SET utf8 ;
USE `reegalo` ;

-- -----------------------------------------------------
-- Table `reegalo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `rol` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `last_login` DATE NULL,
  `last_date_password` DATE NULL,
  `language` VARCHAR(100) NULL,
  `country` VARCHAR(150) NULL,
  `brday` DATE NULL,
  `residence` VARCHAR(150) NULL,
  `phone` VARCHAR(50) NULL,
  `dark_mode` CHAR(1) NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`suppliers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `description` VARCHAR(700) NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `supplier_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `expiration_days` SMALLINT NOT NULL,
  `share` VARCHAR(100) NULL,
  `price` DECIMAL NOT NULL,
  `discount` DECIMAL NULL,
  `life_date_from` DATE NOT NULL,
  `life_date_to` DATE NOT NULL,
  `stock` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_suppliers_idx` (`supplier_id` ASC) ,
  INDEX `fk_products_categories1_idx` (`category_id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  INDEX `user_id_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_products_suppliers`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `reegalo`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `reegalo`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `reegalo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(300) NULL,
  `score` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coments_users1_idx` (`user_id` ASC) ,
  INDEX `fk_coments_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_coments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reegalo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coments_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `reegalo`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`statuses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`purchases` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `purchase_date` DATE NULL,
  `total` DECIMAL NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_users1_idx` (`user_id` ASC) ,
  INDEX `fk_purchases_statuses1_idx` (`status_id` ASC) ,
  CONSTRAINT `fk_invoice_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reegalo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchases_statuses1`
    FOREIGN KEY (`status_id`)
    REFERENCES `reegalo`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`purchase_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`purchase_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchase_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL NOT NULL,
  `discount` DECIMAL NULL,
  `expiration_days` SMALLINT NULL,
  INDEX `fk_invoice_has_products_products1_idx` (`product_id` ASC) ,
  INDEX `fk_invoice_has_products_invoice1_idx` (`purchase_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_invoice_has_products_invoice1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `reegalo`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `reegalo`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`product_image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `number` TINYINT NULL,
  INDEX `fk_products_images_1_idx` (`product_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_images1`
    FOREIGN KEY (`product_id`)
    REFERENCES `reegalo`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`recipients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`recipients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`recipient_purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`recipient_purchase` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(500) NULL,
  `purchase_id` INT UNSIGNED NOT NULL,
  `recipient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `purchase_id_idx` (`purchase_id` ASC) ,
  INDEX `recipient_id_idx` (`recipient_id` ASC) ,
  CONSTRAINT `purchase_id`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `reegalo`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recipient_id`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `reegalo`.`recipients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`questions_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`questions_answers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(150) NOT NULL,
  `answer` VARCHAR(700) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`carts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_number` INT NOT NULL,
  `total` DECIMAL NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `users_idx` (`user_id` ASC) ,
  CONSTRAINT `users0`
    FOREIGN KEY (`user_id`)
    REFERENCES `reegalo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reegalo`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reegalo`.`items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sale_price` DECIMAL(10,0) NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `state` TINYINT(2) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `seller_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `cart_id` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `users_idx` (`user_id` ASC) ,
  INDEX `carts_idx` (`cart_id` ASC) ,
  INDEX `products_idx` (`product_id` ASC) ,
  CONSTRAINT `users`
    FOREIGN KEY (`user_id`)
    REFERENCES `reegalo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carts`
    FOREIGN KEY (`cart_id`)
    REFERENCES `reegalo`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `products`
    FOREIGN KEY (`product_id`)
    REFERENCES `reegalo`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `reegalo`.`categories` -- insert
-- -----------------------------------------------------
insert into categories values ('1','Gastronomia','Gastronomia');
insert into categories values ('2','Aire Libre','Aire Libre');
insert into categories values ('3','Espectaculos','Espectaculos');
insert into categories values ('4','Conocimientos','Conocimientos');
insert into categories values ('5','Experiencias Unicas','Experiencias Unicas');
insert into categories values ('6','Lugares para Conocer','Lugares para Conocer');

-- -----------------------------------------------------
-- Table `reegalo`.`users` -- insert
-- -----------------------------------------------------
insert into users values ('1','Administrador','Admin','admin@dh.com','$2a$10$DVBpNXgqc7nfxk6wnZCg/.oQ39UFnMWznKqmOIiO93zx9OzxQJ3Ri','admin','profile-admin@dh.com.jpg','2020-12-20','2020-12-20','esp','','2020-12-12','','','n','active');
insert into users values ('2','Usuario General','User','user@dh.com','$2a$10$j0gnUS5gdzaji1ICXUSZKOs6CAqC23Fl/Z4Pd.oTnqWrJZ9yRXQv6','user','profile-user@dh.com.jpg','2020-12-21','2020-12-21','esp','','2020-12-10','','','n','active');

-- -----------------------------------------------------
-- Table `reegalo`.`suppliers` -- insert
-- -----------------------------------------------------
insert into suppliers values ('1','Blogtag','Razon Social Blogtag','Habilitado');
insert into suppliers values ('2','Vinder','Razon Social Vinder','Habilitado');
insert into suppliers values ('3','Eimbee','Razon Social Eimbee','Inhabilitado');
insert into suppliers values ('4','Quimm','Razon Social Quimm','Inhabilitado');
insert into suppliers values ('5','Skippad','Razon Social Skippad','Inhabilitado');
insert into suppliers values ('6','Voolia','Razon Social Voolia','Inhabilitado');
insert into suppliers values ('7','Einti','Razon Social Einti','Habilitado');
insert into suppliers values ('8','Dynazzy','Razon Social Dynazzy','Habilitado');
insert into suppliers values ('9','Devbug','Razon Social Devbug','Habilitado');
insert into suppliers values ('10','Leexo','Razon Social Leexo','Habilitado');
insert into suppliers values ('11','Tagfeed','Razon Social Tagfeed','Inhabilitado');
insert into suppliers values ('12','Trilith','Razon Social Trilith','Habilitado');
insert into suppliers values ('13','Muxo','Razon Social Muxo','Inhabilitado');
insert into suppliers values ('14','Ozu','Razon Social Ozu','Inhabilitado');
insert into suppliers values ('15','Brainbox','Razon Social Brainbox','Habilitado');
insert into suppliers values ('16','Riffwire','Razon Social Riffwire','Habilitado');
insert into suppliers values ('17','Eidel','Razon Social Eidel','Habilitado');
insert into suppliers values ('18','Trudeo','Razon Social Trudeo','Inhabilitado');
insert into suppliers values ('19','Teklist','Razon Social Teklist','Inhabilitado');
insert into suppliers values ('20','Dabfeed','Razon Social Dabfeed','Habilitado');
insert into suppliers values ('21','Linkbridge','Razon Social Linkbridge','Habilitado');
insert into suppliers values ('22','Midel','Razon Social Midel','Inhabilitado');
insert into suppliers values ('23','Photofeed','Razon Social Photofeed','Inhabilitado');
insert into suppliers values ('24','Skinder','Razon Social Skinder','Habilitado');
insert into suppliers values ('25','Brainbox_1','Razon Social Brainbox','Habilitado');
insert into suppliers values ('26','Oozz','Razon Social Oozz','Inhabilitado');
insert into suppliers values ('27','Eare','Razon Social Eare','Habilitado');
insert into suppliers values ('28','Divape','Razon Social Divape','Habilitado');
insert into suppliers values ('29','Edgetag','Razon Social Edgetag','Inhabilitado');
insert into suppliers values ('30','Skippad_1','Razon Social Skippad','Habilitado');
insert into suppliers values ('31','Voomm','Razon Social Voomm','Inhabilitado');
insert into suppliers values ('32','Tazzy','Razon Social Tazzy','Habilitado');
insert into suppliers values ('33','Abata','Razon Social Abata','Habilitado');
insert into suppliers values ('34','Fivechat','Razon Social Fivechat','Inhabilitado');
insert into suppliers values ('35','LiveZ','Razon Social LiveZ','Inhabilitado');
insert into suppliers values ('36','Photobug','Razon Social Photobug','Inhabilitado');
insert into suppliers values ('37','Avamm','Razon Social Avamm','Habilitado');
insert into suppliers values ('38','Aimbu','Razon Social Aimbu','Inhabilitado');
insert into suppliers values ('39','Eimbee_1','Razon Social Eimbee','Inhabilitado');
insert into suppliers values ('40','Feedfish','Razon Social Feedfish','Inhabilitado');
insert into suppliers values ('41','Yotz','Razon Social Yotz','Inhabilitado');
insert into suppliers values ('42','Kazio','Razon Social Kazio','Inhabilitado');
insert into suppliers values ('43','Jetpulse','Razon Social Jetpulse','Inhabilitado');
insert into suppliers values ('44','Meeveo','Razon Social Meeveo','Habilitado');
insert into suppliers values ('45','Oyoloo','Razon Social Oyoloo','Inhabilitado');
insert into suppliers values ('46','Flashdog','Razon Social Flashdog','Habilitado');
insert into suppliers values ('47','Edgetag_1','Razon Social Edgetag','Inhabilitado');
insert into suppliers values ('48','Dabfeed_1','Razon Social Dabfeed','Habilitado');
insert into suppliers values ('49','Voolia_1','Razon Social Voolia','Inhabilitado');
insert into suppliers values ('50','Livepath','Razon Social Livepath','Habilitado');
insert into suppliers values ('51','Jaxspan','Razon Social Jaxspan','Inhabilitado');
insert into suppliers values ('52','Jaloo','Razon Social Jaloo','Inhabilitado');
insert into suppliers values ('53','Wikivu','Razon Social Wikivu','Habilitado');
insert into suppliers values ('54','Jabberbean','Razon Social Jabberbean','Habilitado');
insert into suppliers values ('55','Tagpad','Razon Social Tagpad','Habilitado');
insert into suppliers values ('56','Skyble','Razon Social Skyble','Inhabilitado');
insert into suppliers values ('57','Twiyo','Razon Social Twiyo','Inhabilitado');
insert into suppliers values ('58','Riffwire_1','Razon Social Riffwire','Inhabilitado');
insert into suppliers values ('59','Realfire','Razon Social Realfire','Habilitado');
insert into suppliers values ('60','Jabberbean_1','Razon Social Jabberbean','Habilitado');
insert into suppliers values ('61','Centizu','Razon Social Centizu','Habilitado');
insert into suppliers values ('62','Tagfeed_2','Razon Social Tagfeed','Inhabilitado');
insert into suppliers values ('63','Riffpedia','Razon Social Riffpedia','Habilitado');
insert into suppliers values ('64','Linktype','Razon Social Linktype','Habilitado');
insert into suppliers values ('65','Brightdog','Razon Social rightdog','Inhabilitado');
insert into suppliers values ('66','Blogtag_2','Razon Social Blogtag','Inhabilitado');
insert into suppliers values ('67','Topdrive','Razon Social Topdrive','Inhabilitado');
insert into suppliers values ('68','Viva','Razon Social Viva','Inhabilitado');
insert into suppliers values ('69','Agivu','Razon Social givu','Habilitado');
insert into suppliers values ('70','Riffwire_2','Razon Social Riffwire','Inhabilitado');
insert into suppliers values ('71','Zoomdog','Razon Social Zoomdog','Inhabilitado');
insert into suppliers values ('72','Pixonyx','Razon Social Pixonyx','Habilitado');
insert into suppliers values ('73','Zoombox','Razon Social Zoombox','Habilitado');
insert into suppliers values ('74','Wikibox','Razon Social Wikibox','Habilitado');
insert into suppliers values ('75','Tagtune','Razon Social Tagtune','Habilitado');
insert into suppliers values ('76','Kwinu','Razon Social Kwinu','Inhabilitado');
insert into suppliers values ('77','Brightdog_2','Razon Social Brightdog','Habilitado');
insert into suppliers values ('78','Feedmix','Razon Social Feedmix','Inhabilitado');
insert into suppliers values ('79','Edgetag_2','Razon Social Edgetag','Inhabilitado');
insert into suppliers values ('80','Photolist','Razon Social Photolist','Inhabilitado');
insert into suppliers values ('81','Voonix','Razon Social Voonix','Habilitado');
insert into suppliers values ('82','Wikizz','Razon Social Wikizz','Inhabilitado');
insert into suppliers values ('83','Jabbercube','Razon Social Jabbercube','Habilitado');
insert into suppliers values ('84','Twitterworks','Razon Social Twitterworks','Inhabilitado');
insert into suppliers values ('85','Ntags','Razon Social Ntags','Inhabilitado');
insert into suppliers values ('86','Oyoba','Razon Social Oyoba','Inhabilitado');
insert into suppliers values ('87','Babbleset','Razon Social Babbleset','Inhabilitado');
insert into suppliers values ('88','Trilith_3','Razon Social Trilith','Inhabilitado');
insert into suppliers values ('89','Meetz','Razon Social Meetz','Inhabilitado');
insert into suppliers values ('90','Janyx','Razon Social Janyx','Inhabilitado');
insert into suppliers values ('91','Wordify','Razon Social Wordify','Inhabilitado');
insert into suppliers values ('92','Vinder_3','Razon Social Vinder','Habilitado');
insert into suppliers values ('93','Dabshots','Razon Social Dabshots','Habilitado');
insert into suppliers values ('94','Twiyo_3','Razon Social Twiyo','Inhabilitado');
insert into suppliers values ('95','Jaxworks','Razon Social Jaxworks','Habilitado');
insert into suppliers values ('96','Blogtags','Razon Social Blogtags','Inhabilitado');
insert into suppliers values ('97','Skimia','Razon Social Skimia','Inhabilitado');
insert into suppliers values ('98','Jabberbean_3','Razon Social Jabberbean','Habilitado');
insert into suppliers values ('99','Shufflester','Razon Social Shufflester','Habilitado');
insert into suppliers values ('100','Muxo_4','Razon Social Muxo','Habilitado');

-- -----------------------------------------------------
-- Table `reegalo`.`products` -- insert
-- -----------------------------------------------------
insert into products values (1,'Lo mejor de la comida Italiana en Buenos Aires','Para los amantes de la comida italiana , las mejores pasta hechas a manos por sus dueÃ±os. Tradicion desde 1964. Ideal para compartir!',1,100,'2020-10-09',365,'Para Compartir x 2',2040,5,'2021-01-01','2021-03-31',50,'Habilitado',1);
insert into products values (2,'Delicias para el paladar','Nuestro Top 3 para vivir la fusion perfecta de sabores. El carta tiene comidas de distintas nacionalidades, lo que le da al visitante una variable infinita ',1,2,'2020-10-09',365,'Para Compartir x 2',1216,5,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (3,'Date un gusto distinto','Tres propuestas para transportarse a tierras lejanas desde el primer bocado.',1,8,'2020-10-09',365,'Individual',1876,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (4,'Comida rapida de calidad','Una experiencia que combina vinos & conservas seleccionadas creando perfectos maridajes. Una propuesta especial para amantes del vino y de los buenos sabores.',1,8,'2020-10-09',365,'Para Compartir x 2',1050,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (5,'Comemos algo tipico?','La mejor pasteleria de Santa Fe para disfrutar en la comodidad de tu casa. La combinacion perfecta, y si lo acompanias con un cafe, es imposible resistirse!',1,8,'2020-10-09',365,'Individual',1265,10,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (6,'Paseo por el rosedal','Paseo por el lugar con hermosas rosas',2,12,'2020-10-09',365,'Para Compartir x 2',1952,5,'2020-10-09','2021-12-09',12,'Habilitado',1);
insert into products values (7,'Cine al aire libre','Auto y cine, que mas se puede pedir. En los tiempos que corren lo importante es divertirse pero en modo seguro. Te ofrecemos una experiencia que cumple con todo!',2,7,'2020-10-09',365,'Individual',1842,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (8,'Paseo por el rio en velero','Amanecer, vino y agua',2,8,'2020-10-09',365,'Para Compartir x 2',1231,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (9,'Paseo por lugares con historia','Todo lo que tenes que saber de la capital lo encontras aca. Pasea por lugares que tiene historia y conoce tus secretos...',2,9,'2020-10-09',365,'Individual',1751,10,'2020-10-09','2021-07-09',12,'Habilitado',1);
insert into products values (12,'Teatro Colon Buenos Aires','Elegi la funcion en nuestra pagina',3,2,'2020-10-09',365,'Para Compartir x 2',1962,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (13,'Comedia para no parar de reir','No vas a poder dejar de reirte de los chistes que nos cuenta Alejandro Villafane. Lo mejor del Stand-up en Buenos Aires',3,8,'2020-10-09',365,'Individual',1457,10,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (14,'Concierto de Kumiko Miyagui en el teatro Colon','Cinco unicas funciones de Kumiko Miyagui en el teatro Colon. Imperdible para los amantes del lo clasico!',3,8,'2020-10-09',365,'Para Compartir x 2',1266,5,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (15,'Casados con hijos','Tipica familia en vivo, algo que no te podes perder.',3,9,'2020-10-09',365,'Individual',1748,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (16,'Piano como Beethoven ','4 clases de piano con un reconocido profesor. Mentor de grandes pianistas nacionales',4,15,'2020-10-09',365,'Para Compartir x 2',1008,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (17,'Aprende de Marketing Digital','5 clases de marketing para saber usar redes sociales',4,7,'2020-10-09',365,'Individual',1056,10,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (18,'Perfeccionate en el arte de la guitarra','Aprende los secretos de los mejores guitarristas. Nos adaptamos a tu estilo. Te esperamos!',4,8,'2020-10-09',365,'Para Compartir x 2',1486,5,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (19,'Programacion Web Full Stack en Digital House','Convertite en un experto aprendiendo en Digital House. Curso de Programacion Web Full Stack. Duracion 6 meses',4,9,'2020-10-09',365,'Individual',1542,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (20,'Pintar te libera','6 clases de pintura donde vos podras sacar el artista que hay dentro tuyo. La pintura es una de la expresiones personales. Experimentalo!',4,10,'2020-10-09',365,'Para Compartir x 2',1828,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (21,'Volar en paracaidas','10 segundos de pura adrenalina',5,1,'2020-10-09',365,'Individual',1483,10,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (22,'Experiencia unica en Parapente','Una vista que no te podes perder. Animate a sentirte como un pajaro! Nosotros te ayudamos!',5,2,'2020-10-09',365,'Para Compartir x 2',1586,5,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (23,'Paintball en el bosque ','Divertite a lo maximo con tus amigos. Descarga tensiones y disfruta de la adrenalina de un combate seguro. Tenemos todas las medidas de seguridad para que lo disfrutes a pleno!',5,12,'2020-10-09',365,'Para Compartir x 2',1506,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (24,'Da tus primeros pasos en Sky','Para vos que siempre te gusto el arte del sky , da tus primeros pasos. Te ayudamos a hacerlo en un ambiente seguro y agradable!',5,12,'2020-10-09',365,'Para Compartir x 2',1602,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (25,'Buceo, ser parte del mar','Agua para los que no le tienen miedo a los tiburones',5,16,'2020-10-09',365,'Individual',1363,10,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (27,'Puerto Madero de Tarde','Puerto Madero es uno de los lugares mas exclusivos de la Capital Federal. Animate a conocerlo!',6,7,'2020-10-09',365,'Individual',1726,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (28,'Escapada a Cordoba','Cordoba, lo mejor de las sierras argentinas. Un lugares para descansar y disfrutar de los platos tipicos!',6,8,'2020-10-09',365,'Para Compartir x 2',1542,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (29,'Bariloche nos encanta','Bariloche con sus lagos son unicos en el mundo. Veni y disfrutanos, No lo vas a olvidar!',6,9,'2020-10-09',365,'Individual',1097,20,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (30,'Quiero ir a alguna parte','Escapate un fin de semana a Neuquen',6,10,'2020-10-09',365,'Para Compartir x 2',1752,0,'2020-10-09','2021-10-09',12,'Habilitado',1);
insert into products values (32,'Tour de compras por New York','New York es una ciudad fascinante y mucho mas si vas de compras. Te guiamos a partir de tus preferencias en los mejores shoopings neoyorquinos!',6,15,'2020-11-09',365,'Para Compartir x 2',2500,10,'2020-11-09','2021-11-09',15,'Habilitado',1);
insert into products values (35,'Palotes de primera','Una cena en Palotes. No podes perderte de la hamburguesa Palotes con doble cheddar, panceta, pepinos y unas papas rusticas increibles.',1,7,'2020-11-16',300,'Individual',2000,20,'2020-12-01','2021-02-18',2,'Habilitado',1);
insert into products values (38,'Visitas al planetario de Buenos Aires','Visitas al planetario de Buenos Aires. Disfrute de la experiencia de ver el universo',6,15,'2020-12-01',365,'Para Compartir x 2',900,0,'2020-12-09','2021-12-17',15,'Habilitado',1);
insert into products values (40,'Solo para los amantes de los dulces','Vivi una experiencia unica degustando postres hecho por los que saben. Para compartir con tus amigos y pasar un lindo momento en un ambiente calido.',1,1,'2020-12-03',200,'Para Compartir x 3',11399,10,'2020-12-03','2021-12-10',10,'Habilitado',1);

-- -----------------------------------------------------
-- Table `reegalo`.`product_image` -- insert
-- -----------------------------------------------------
insert into product_image values (3,3,'Gastronomia.jpg',0);
insert into product_image values (20,21,'parapente.jpg',0);
insert into product_image values (36,40,'image1604975272225.jpg',0);
insert into product_image values (80,1,'image1613749339095.jpg',0);
insert into product_image values (82,35,'image1613749857763.jpg',0);
insert into product_image values (83,7,'image1613750419885.jpg',0);
insert into product_image values (84,8,'image1613750816141.jpg',0);
insert into product_image values (85,9,'image1613750973060.jpg',0);
insert into product_image values (86,6,'image1613751116420.jpg',0);
insert into product_image values (87,12,'image1613751445234.jpg',0);
insert into product_image values (88,14,'image1613751792194.jpg',0);
insert into product_image values (89,13,'image1613752049536.jpg',0);
insert into product_image values (91,38,'image1613752378832.jpg',0);
insert into product_image values (92,19,'image1613752543219.jpg',0);
insert into product_image values (93,17,'image1613752741893.jpg',0);
insert into product_image values (94,16,'image1613752928776.jpg',0);
insert into product_image values (95,20,'image1613753100389.jpg',0);
insert into product_image values (96,24,'image1613753435562.jpg',0);
insert into product_image values (97,25,'image1613753552744.jpg',0);
insert into product_image values (98,22,'image1613753744007.jpg',0);
insert into product_image values (99,23,'image1613754199437.jpg',0);
insert into product_image values (100,32,'image1613754983328.jpg',0);
insert into product_image values (101,29,'image1613755097039.jpg',0);
insert into product_image values (102,28,'image1613755212270.jpg',0);
insert into product_image values (103,27,'image1613755532956.jpg',0);
insert into product_image values (104,30,'image1613755708583.jpg',0);
insert into product_image values (105,5,'image1613756298738.jpg',0);
insert into product_image values (106,18,'image1613757178927.jpg',0);
insert into product_image values (107,2,'image1613759569850.jpg',0);
insert into product_image values (108,4,'image1613759716683.jpg',0);
insert into product_image values (109,15,'image1613760032980.jpg',0);

-- -----------------------------------------------------
-- Table `reegalo`.`comments` -- insert
-- -----------------------------------------------------
insert into comments values (77,2,3,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (78,2,21,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (79,2,40,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (80,2,1,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (82,2,35,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (83,2,7,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (84,2,8,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (85,2,9,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (86,2,6,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (87,2,12,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (88,2,14,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (89,2,13,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (91,2,38,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (92,2,19,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (93,2,17,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (94,2,16,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (95,2,20,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (96,2,24,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (97,2,25,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (98,2,22,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (99,2,23,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (10,2,32,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (11,2,29,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (12,2,28,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (13,2,27,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (14,2,30,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (15,2,5,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (16,2,18,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (17,2,2,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (18,2,4,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (19,2,15,'La experiencia estuvo buenisima. Se las voy a recomerdar a mis amigos','4.5','2020-12-10');
insert into comments values (177,2,3,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (178,2,21,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (179,2,40,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (180,2,1,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (182,2,35,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (183,2,7,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (184,2,8,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (185,2,9,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (186,2,6,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (187,2,12,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (188,2,14,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (189,2,13,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (191,2,38,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (192,2,19,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (193,2,17,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (194,2,16,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (195,2,20,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (196,2,24,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (197,2,25,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (198,2,22,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (199,2,23,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (110,2,32,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (111,2,29,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (112,2,28,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (113,2,27,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (114,2,30,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (115,2,5,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (116,2,18,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (117,2,2,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (118,2,4,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (119,2,15,'Muchas gracias por el reegalo!. A mis amigos le encanto!','4.5','2020-12-10');
insert into comments values (277,2,3,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (278,2,21,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (279,2,40,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (280,2,1,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (282,2,35,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (283,2,7,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (284,2,8,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (285,2,9,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (286,2,6,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (287,2,12,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (288,2,14,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (289,2,13,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (291,2,38,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (292,2,19,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (293,2,17,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (294,2,16,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (295,2,20,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (296,2,24,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (297,2,25,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (298,2,22,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (299,2,23,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (210,2,32,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (211,2,29,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (212,2,28,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (213,2,27,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (214,2,30,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (215,2,5,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (216,2,18,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (217,2,2,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (218,2,4,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');
insert into comments values (219,2,15,'Estoy muy conforme con la experiencia que seleccione. Lo volvieria a regalar!','4.5','2020-12-10');

-- -----------------------------------------------------
-- Table `reegalo`.`questions_answers` -- insert
-- -----------------------------------------------------
insert into questions_answers values ("1","Como hago para regalar?","Elegis el regalo que mas te guste, lo agregas al carrito, pagas y te llega una tarjeta para disfrutar del regalo");
insert into questions_answers values ("2","Si se me está por vencer el regalo, ¿puedo extenderlo?","Vas a poder cambiarlo a crédito (por el valor abonado por tu código) que tendrá vigencia de un año, por otra Bigbox o la misma con nuevo vencimiento a la venta. Luego de los 60 días desde el límite del uso, lamentablemente, no será posible reactivar el código.");
insert into questions_answers values ("3","Quiero unir mis regalos, ¿cómo hago?","Para unir tus regalos deberás convertirlos en crédito. Cambiar Regalo que te permitirá convertir tus regalos en crédito.");
insert into questions_answers values ("4","Como reservar?","Para reservar comunicate directamente con el lugar (los datos de contacto figuran en la descripción!) y hacé tu reserva indicando el código de tu Reegalo. Todas las reservas se realizan con anticipación y se encuentran sujetas a disponibilidad y condiciones del prestador de la experiencia. Las experiencias se deben reservar y realizar durante el plazo de vigencia del Reegalo. Luego de la fecha de vencimiento, el código Reegalo queda inhabilitado y no puede ser utilizado. No es posible realizar una reserva para una fecha posterior al vencimiento.");
insert into questions_answers values ("5","¿Para cuántas personas es el Reegalo?","La cantidad de personas que podrán disfrutar la experiencia dependerá de cada Reegalo y de la actividad seleccionada. Las experiencias varían entre una y dos personas.");
